# Generated by Django 6.0.5 on 2026-05-25 16:57

import django.core.validators
import django.db.models.deletion
import suppliers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('individual', 'Individual Seller'), ('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('limited_company', 'Limited Company'), ('corporation', 'Corporation')], max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('business_phone', models.CharField(max_length=20)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_address', models.TextField()),
                ('business_city', models.CharField(max_length=100)),
                ('business_country', models.CharField(default='Rwanda', max_length=100)),
                ('business_license', models.FileField(help_text='Business registration certificate / license', upload_to=suppliers.models.supplier_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg'])])),
                ('tax_clearance', models.FileField(blank=True, help_text='Tax clearance certificate', null=True, upload_to=suppliers.models.supplier_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg'])])),
                ('id_document', models.FileField(help_text='National ID or Passport', upload_to=suppliers.models.supplier_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg'])])),
                ('bank_statement', models.FileField(blank=True, help_text='Recent bank statement (for payout info)', null=True, upload_to=suppliers.models.supplier_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'jpeg'])])),
                ('additional_documents', models.FileField(blank=True, help_text='Any additional supporting documents', null=True, upload_to=suppliers.models.supplier_document_path)),
                ('website', models.URLField(blank=True)),
                ('years_in_business', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_monthly_volume', models.DecimalField(decimal_places=2, default=0, help_text='Estimated monthly sales volume in FRW', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from supplier')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('additional_info', 'Additional Info Required')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('additional_info_request', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_categories', models.ManyToManyField(blank=True, related_name='interested_suppliers', to='products.category')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application_number'], name='suppliers_s_applica_423731_idx'), models.Index(fields=['status', '-created_at'], name='suppliers_s_status_bdf86e_idx'), models.Index(fields=['business_name'], name='suppliers_s_busines_7008d2_idx'), models.Index(fields=['supplier'], name='suppliers_s_supplie_617a67_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayoutHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('payment_details', models.JSONField(default=dict)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_items', models.ManyToManyField(related_name='payouts', to='orders.orderitem')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Supplier Payout Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payout_number'], name='suppliers_s_payout__c41860_idx'), models.Index(fields=['supplier', '-created_at'], name='suppliers_s_supplie_0ba062_idx'), models.Index(fields=['status'], name='suppliers_s_status_689a32_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_units_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('new_products', models.IntegerField(default=0)),
                ('products_approved', models.IntegerField(default=0)),
                ('products_rejected', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('response_rate', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_date'],
                'unique_together': {('supplier', 'period_date', 'period_type')},
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=suppliers.models.supplier_logo_path)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='suppliers/covers/')),
                ('business_phone', models.CharField(max_length=20)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_address', models.TextField()),
                ('business_city', models.CharField(max_length=100)),
                ('business_country', models.CharField(default='Rwanda', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, help_text='Business description and story')),
                ('years_in_business', models.IntegerField(default=1)),
                ('number_of_employees', models.IntegerField(default=1)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_products_sold', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('response_rate', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('response_time', models.CharField(default='< 1 hour', max_length=50)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Verification Pending'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_documents', models.JSONField(blank=True, default=list)),
                ('payment_method', models.CharField(default='mobile_money', max_length=50)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('bank_account_name', models.CharField(blank=True, max_length=255)),
                ('bank_account_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_approve_products', models.BooleanField(default=False, help_text='Auto-approve products (trusted suppliers only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['supplier'], name='suppliers_s_supplie_9025e6_idx'), models.Index(fields=['verification_status'], name='suppliers_s_verific_669fa2_idx'), models.Index(fields=['average_rating'], name='suppliers_s_average_f74cc0_idx')],
            },
        ),
    ]
