# Generated by Django 6.0.5 on 2026-05-27 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_supplierpayout_supplier_and_more'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayouthistory',
            name='order_items',
            field=models.ManyToManyField(related_name='supplier_payouts_list', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='supplierpayouthistory',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierpayouthistory',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payout_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierperformancemetric',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_performance_metrics', to=settings.AUTH_USER_MODEL),
        ),
    ]
