# Generated by Django 6.0.5 on 2026-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplierpayouthistory_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='business_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='business_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='business_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
