# Generated by Django 6.0.5 on 2026-05-25 16:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('order_processed', 'Order Processed'), ('supplier_approved', 'Supplier Approved'), ('product_approved', 'Product Approved'), ('customer_responded', 'Customer Responded'), ('report_generated', 'Report Generated')], max_length=30)),
                ('description', models.TextField()),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Team Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('ceo', 'CEO / Founder'), ('cto', 'CTO / Technical Director'), ('operations', 'Operations Manager'), ('sales', 'Sales Manager'), ('support', 'Customer Support'), ('marketing', 'Marketing Specialist'), ('procurement', 'Procurement Specialist'), ('logistics', 'Logistics Coordinator'), ('other', 'Other')], max_length=50)),
                ('custom_position', models.CharField(blank=True, help_text="If position is 'Other'", max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(help_text='Short biography of team member')),
                ('expertise', models.TextField(blank=True, help_text='Areas of expertise, comma separated')),
                ('achievements', models.TextField(blank=True, help_text='Key achievements')),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower number appears first')),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('tasks_completed', models.IntegerField(default=0)),
                ('customer_satisfaction', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_display', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-joined_at'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='team_teamme_is_acti_dbf1bf_idx'), models.Index(fields=['featured'], name='team_teamme_feature_c89cc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('due_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('related_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='team_teamta_assigne_f91d66_idx'), models.Index(fields=['due_date'], name='team_teamta_due_dat_0f940f_idx')],
            },
        ),
    ]
