# Generated by Django 6.0.5 on 2026-05-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='dashboard_n_user_id_5c2164_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='dashboard_n_user_id_b572f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='dashboard_n_notific_47e787_idx',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
