# Generated by Django 6.0.5 on 2026-06-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginhistory',
            name='browser_display',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='device_brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='device_display',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='device_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='location_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='os_display',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='device_type',
            field=models.CharField(choices=[('pc', 'PC/Laptop'), ('smartphone', 'Smartphone'), ('tablet', 'Tablet'), ('bot', 'Bot/Crawler'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='os_type',
            field=models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('chromeos', 'Chrome OS'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userloginhistory',
            index=models.Index(fields=['device_type'], name='accounts_us_device__aa586a_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginhistory',
            index=models.Index(fields=['os_type'], name='accounts_us_os_type_f21e84_idx'),
        ),
    ]
