# Generated by Django 6.0.5 on 2026-06-12 09:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_type', models.CharField(choices=[('admin', 'Admin Commission Wallet'), ('supplier', 'Supplier Earnings Wallet'), ('tax', 'Tax Collection Wallet')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Money In)'), ('debit', 'Debit (Money Out)')], max_length=20)),
                ('category', models.CharField(choices=[('commission', 'Admin Commission'), ('supplier_payout', 'Supplier Payout'), ('vat_collection', 'VAT Collection'), ('product_sale', 'Product Sale'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='adjustment', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='withdrawalrequest',
            name='orders_with_request_ef7a52_idx',
        ),
        migrations.RemoveIndex(
            model_name='withdrawalrequest',
            name='orders_with_admin_i_3b5002_idx',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='rejection_reason',
            new_name='failure_reason',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], default='mobile_money', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_number',
            field=models.CharField(default='LEGACY-WITHDRAWAL-001', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000'))]),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='orders.wallet'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['withdrawal_number'], name='orders_with_withdra_50a6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'status'], name='orders_with_user_id_acbd87_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['created_at'], name='orders_with_created_6d6f98_idx'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.wallet'),
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='mobile_money_number',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='request_reference',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='reviewed_by',
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'wallet_type'], name='orders_wall_user_id_e951bc_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['wallet_type'], name='orders_wall_wallet__854428_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='orders_wall_wallet__0c39d1_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference'], name='orders_wall_referen_8e7595_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['category'], name='orders_wall_categor_b875b4_idx'),
        ),
    ]
