# Generated by Django 6.0.5 on 2026-05-27 13:59

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_path),
        ),
    ]
